-- Migration: player-prop model versioning, calibration tracking, and learned weights.

alter table public.scan_opportunities
  add column if not exists first_model_key text,
  add column if not exists last_model_key text,
  add column if not exists close_opposing_reference_odds double precision,
  add column if not exists close_true_prob double precision,
  add column if not exists close_quality text;

create table if not exists public.scan_opportunity_model_evaluations (
  id bigint generated by default as identity primary key,
  opportunity_key text not null,
  model_key text not null,
  capture_role text not null,
  surface text not null,
  sport text not null,
  event text not null,
  team text,
  sportsbook text not null,
  sportsbook_key text not null,
  market text not null,
  event_id text,
  player_name text,
  selection_side text,
  line_value double precision,
  reference_source text,
  first_source text,
  last_source text,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  first_true_prob double precision,
  last_true_prob double precision,
  first_raw_true_prob double precision,
  last_raw_true_prob double precision,
  first_book_odds double precision,
  last_book_odds double precision,
  first_book_decimal double precision,
  last_book_decimal double precision,
  first_reference_odds double precision,
  last_reference_odds double precision,
  first_ev_percentage double precision,
  last_ev_percentage double precision,
  first_confidence_score double precision,
  last_confidence_score double precision,
  first_confidence_label text,
  last_confidence_label text,
  first_reference_bookmaker_count integer,
  last_reference_bookmaker_count integer,
  first_interpolation_mode text,
  last_interpolation_mode text,
  first_reference_inputs_json jsonb,
  last_reference_inputs_json jsonb,
  first_prob_std double precision,
  last_prob_std double precision,
  first_shrink_factor double precision,
  last_shrink_factor double precision,
  close_reference_odds double precision,
  close_opposing_reference_odds double precision,
  close_true_prob double precision,
  close_quality text,
  close_captured_at timestamptz,
  first_clv_ev_percent double precision,
  last_clv_ev_percent double precision,
  first_beat_close boolean,
  last_beat_close boolean,
  first_brier_score double precision,
  last_brier_score double precision,
  first_log_loss double precision,
  last_log_loss double precision
);

create unique index if not exists scan_opportunity_model_evaluations_opportunity_model_idx
  on public.scan_opportunity_model_evaluations (opportunity_key, model_key);

create index if not exists scan_opportunity_model_evaluations_model_idx
  on public.scan_opportunity_model_evaluations (model_key, close_captured_at desc);

create index if not exists scan_opportunity_model_evaluations_market_book_idx
  on public.scan_opportunity_model_evaluations (market, sportsbook_key, close_captured_at desc);

create table if not exists public.player_prop_model_weights (
  id bigint generated by default as identity primary key,
  model_family text not null,
  market_key text not null,
  sportsbook_key text not null,
  weight double precision not null,
  sample_count integer not null default 0,
  weighted_mae double precision,
  updated_at timestamptz not null default now()
);

create unique index if not exists player_prop_model_weights_family_market_book_idx
  on public.player_prop_model_weights (model_family, market_key, sportsbook_key);
