-- ============================================================
-- Migration 023: Player-prop model candidate observations
-- ============================================================
-- Backend-only research table for comparing ops-only shadow model
-- candidate sets against the live player-prop model.

CREATE TABLE IF NOT EXISTS public.player_prop_model_candidate_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_set_key TEXT NOT NULL,
  source TEXT NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL,
  model_key TEXT NOT NULL,
  opportunity_key TEXT NOT NULL,
  rank_overall INTEGER,
  rank_displayed INTEGER,
  cohort TEXT NOT NULL DEFAULT 'quality_gated',
  surface TEXT NOT NULL DEFAULT 'player_props',
  sport TEXT NOT NULL,
  event TEXT NOT NULL,
  event_id TEXT,
  commence_time TIMESTAMPTZ,
  sportsbook TEXT NOT NULL,
  sportsbook_key TEXT,
  market TEXT NOT NULL,
  market_key TEXT,
  player_name TEXT,
  participant_id TEXT,
  selection_side TEXT,
  line_value DOUBLE PRECISION,
  book_odds DOUBLE PRECISION,
  book_decimal DOUBLE PRECISION,
  reference_source TEXT,
  reference_odds DOUBLE PRECISION,
  true_prob DOUBLE PRECISION,
  raw_true_prob DOUBLE PRECISION,
  ev_percentage DOUBLE PRECISION,
  base_kelly_fraction DOUBLE PRECISION,
  confidence_label TEXT,
  confidence_score DOUBLE PRECISION,
  prob_std DOUBLE PRECISION,
  reference_bookmaker_count INTEGER,
  filtered_reference_count INTEGER,
  exact_reference_count INTEGER,
  interpolated_reference_count INTEGER,
  interpolation_mode TEXT,
  reference_bookmakers JSONB,
  reference_inputs_json JSONB,
  shrink_factor DOUBLE PRECISION,
  close_reference_odds DOUBLE PRECISION,
  close_opposing_reference_odds DOUBLE PRECISION,
  close_true_prob DOUBLE PRECISION,
  close_quality TEXT,
  close_captured_at TIMESTAMPTZ,
  clv_ev_percent DOUBLE PRECISION,
  beat_close BOOLEAN,
  brier_score DOUBLE PRECISION,
  log_loss DOUBLE PRECISION
);

CREATE UNIQUE INDEX IF NOT EXISTS player_prop_model_candidate_observations_set_model_opp_idx
  ON public.player_prop_model_candidate_observations (candidate_set_key, model_key, opportunity_key);

CREATE INDEX IF NOT EXISTS player_prop_model_candidate_observations_model_captured_idx
  ON public.player_prop_model_candidate_observations (model_key, captured_at DESC);

CREATE INDEX IF NOT EXISTS player_prop_model_candidate_observations_opp_idx
  ON public.player_prop_model_candidate_observations (opportunity_key);

ALTER TABLE public.player_prop_model_candidate_observations ENABLE ROW LEVEL SECURITY;
