-- ============================================================
-- Migration 018: Player-prop weights + backend-only research RLS
-- ============================================================
-- These tables are written and read by the backend service-role
-- client only. Enabling RLS blocks direct anon/authenticated API
-- access while preserving backend behavior.

ALTER TABLE IF EXISTS public.scan_opportunity_model_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pickem_research_observations ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.player_prop_model_weights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_family TEXT NOT NULL,
  market_key TEXT NOT NULL,
  sportsbook_key TEXT NOT NULL,
  weight DOUBLE PRECISION NOT NULL,
  sample_count INTEGER NOT NULL DEFAULT 0,
  weighted_mae DOUBLE PRECISION,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS player_prop_model_weights_family_market_book_idx
  ON public.player_prop_model_weights (model_family, market_key, sportsbook_key);

ALTER TABLE public.player_prop_model_weights ENABLE ROW LEVEL SECURITY;

