-- ============================================================
-- Migration 012: Research model-versioning and calibration tables
-- ============================================================

ALTER TABLE public.scan_opportunities
  ADD COLUMN IF NOT EXISTS first_model_key TEXT,
  ADD COLUMN IF NOT EXISTS last_model_key TEXT,
  ADD COLUMN IF NOT EXISTS close_opposing_reference_odds DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS close_true_prob DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS close_quality TEXT;

CREATE TABLE IF NOT EXISTS public.scan_opportunity_model_evaluations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_key TEXT NOT NULL,
  model_key TEXT NOT NULL,
  capture_role TEXT NOT NULL,
  surface TEXT NOT NULL,
  sport TEXT NOT NULL,
  event TEXT NOT NULL,
  team TEXT,
  sportsbook TEXT NOT NULL,
  sportsbook_key TEXT NOT NULL,
  market TEXT NOT NULL,
  event_id TEXT,
  player_name TEXT,
  selection_side TEXT,
  line_value DOUBLE PRECISION,
  reference_source TEXT,
  first_source TEXT,
  last_source TEXT,
  first_seen_at TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ,
  first_true_prob DOUBLE PRECISION,
  last_true_prob DOUBLE PRECISION,
  first_raw_true_prob DOUBLE PRECISION,
  last_raw_true_prob DOUBLE PRECISION,
  first_book_odds DOUBLE PRECISION,
  last_book_odds DOUBLE PRECISION,
  first_book_decimal DOUBLE PRECISION,
  last_book_decimal DOUBLE PRECISION,
  first_reference_odds DOUBLE PRECISION,
  last_reference_odds DOUBLE PRECISION,
  first_ev_percentage DOUBLE PRECISION,
  last_ev_percentage DOUBLE PRECISION,
  first_confidence_score DOUBLE PRECISION,
  last_confidence_score DOUBLE PRECISION,
  first_confidence_label TEXT,
  last_confidence_label TEXT,
  first_reference_bookmaker_count INTEGER,
  last_reference_bookmaker_count INTEGER,
  first_interpolation_mode TEXT,
  last_interpolation_mode TEXT,
  first_reference_inputs_json JSONB,
  last_reference_inputs_json JSONB,
  first_prob_std DOUBLE PRECISION,
  last_prob_std DOUBLE PRECISION,
  first_shrink_factor DOUBLE PRECISION,
  last_shrink_factor DOUBLE PRECISION,
  close_reference_odds DOUBLE PRECISION,
  close_opposing_reference_odds DOUBLE PRECISION,
  close_true_prob DOUBLE PRECISION,
  close_quality TEXT,
  close_captured_at TIMESTAMPTZ,
  first_clv_ev_percent DOUBLE PRECISION,
  last_clv_ev_percent DOUBLE PRECISION,
  first_beat_close BOOLEAN,
  last_beat_close BOOLEAN,
  first_brier_score DOUBLE PRECISION,
  last_brier_score DOUBLE PRECISION,
  first_log_loss DOUBLE PRECISION,
  last_log_loss DOUBLE PRECISION
);

CREATE UNIQUE INDEX IF NOT EXISTS scan_opportunity_model_evaluations_opportunity_model_idx
  ON public.scan_opportunity_model_evaluations (opportunity_key, model_key);

CREATE INDEX IF NOT EXISTS scan_opportunity_model_evaluations_model_idx
  ON public.scan_opportunity_model_evaluations (model_key, close_captured_at DESC);

CREATE INDEX IF NOT EXISTS scan_opportunity_model_evaluations_market_book_idx
  ON public.scan_opportunity_model_evaluations (market, sportsbook_key, close_captured_at DESC);
